<?php

namespace AppBundle\Repository;

/**
 * FavoriteformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteformationRepository extends \Doctrine\ORM\EntityRepository
{
}
