<?php

namespace AppBundle\Repository;

/**
 * FormationPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationPageRepository extends \Doctrine\ORM\EntityRepository
{
}
