<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{

    public function findFormation(array $searchs)
    {

        $query = $this->createQueryBuilder('a');

        foreach ($searchs as $search) {

            $query->orWhere('a.title LIKE :title')
                  ->orWhere('a.description LIKE :description')
                  ->setParameter('title', '%' . $search . '%')
                  ->setParameter('description', '%' . $search . '%');

            $formation[] = $query->getQuery()->getResult();
    }

        foreach ($formation as $formation) {

            foreach ($formation as $result) {

                $results[] = $result;
            }
        }
            return $results;
    }
}
