# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    access_control:

       - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        AppBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        our_db_provider:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:

            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                provider: our_db_provider
            logout:
                            path:    /logout
                            target: /
            remember_me:
                            secret:   '%secret%'
                            lifetime: 604800 # 1 week in seconds
                            path:     /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/formation, roles: [ROLE_ADMIN, ROLE_USER] }


            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
