<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6nwge0k\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6nwge0k/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6nwge0k.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6nwge0k\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6nwge0k\appDevDebugProjectContainer(array(
    'container.build_hash' => '6nwge0k',
    'container.build_id' => 'b21d0dec',
    'container.build_time' => 1526477947,
), __DIR__.\DIRECTORY_SEPARATOR.'Container6nwge0k');
